### ISSUE TITLE
update后可以给对象里的version自动+1吗

### ISSUE THREAD

**Issue by zccold** [go-gorm/optimisticlock#11]
目前我是在用AfterUpdate钩子实现的，不过这样得给所有用到的类型都加上AfterUpdate，想知道有没有办法在插件里实现

**Comment by icpd** [comment]
没办法，插件内只是组装语句的逻辑，没法得到最后DB执行后的结果

**Comment by jesse-engineer** [comment]
> 插件在数据库写入之前执行，没法得到数据库执行后的结果

只需要判断是否更新成功，如果成功给version变量直接+1即可吧。

**Comment by icpd** [comment]
> 判断是否更新

你说的是否更新就是执行后的结果。
当前仓库使用的是自定义数据类型 Hooks，只会在 SQL 生成阶段执行。

想要更新 version 可以通过实现 gorm.Plugin 注册回调实现。
