### ISSUE TITLE
making the optimisticlock plugin work with gorm v1.22.5

### ISSUE THREAD

**Issue by ravirajsdeshmukh** [go-gorm/optimisticlock#20]
The version column is not incrementing when using the optimistic lock plugin with gorm v1.22.5. Below is the generated query.

UPDATE "<table-name>" SET "name"='name-1',"created_timestamp"='2022-11-30 12:56:05.62',"updated_timestamp"='2022-11-30 14:49:04.531',"sync_timestamp"='0000-00-00 00:00:00',"created_by"='',"updated_by"='',"o_version"=1, "status"='Available' WHERE "uuid" = '327250f2-c77f-4996-b8a1-7ec7c76c1e0a' AND "<table-name>"."o_version" = 1

"o_version" is name of the column used for optimistic locking.

type Common struct {
   UUID             uuid.UUID              `gorm:"primaryKey" json:"uuid,omitempty"`
   Name             string                 `gorm:"not null;unique" json:"name,omitempty"`
   OVersion         optimisticlock.Version `json:"oVersion,omitempty"`
}

As you can see in the generated query the updated clause contains "o_version"=1, but according to implementation it should contain an SQL query of form "o_version"="o_version"+1 for optimistic locking to work properly. Your help will be greatly appreciated.

**Comment by icpd** [comment]
Yes, this version will cause the plugin's set value to be lost. Fixed in gorm v1.23.2.
You are advised to upgrade gorm to the latest version.

**Comment by ravirajsdeshmukh** [comment]
Thanks for the reply. We may not be able to upgrade as that will require agreement from all stakeholders and extensive testing. Is there any workaround? 
May be a local patch on top of optimistic lock plugin or gorm v1.22.5 itself?

**Comment by ravirajsdeshmukh** [comment]
If we add following snippet in the version.go it seems to be working with the version of gorm that we are using.

	if c, ok := stmt.Clauses["SET"]; ok {
		if set, ok := c.Expression.(clause.Set); ok && len(set) > 1 {
			for idx, expr := range set {
				if expr.Column.Name == v.Field.DBName {
					set[idx].Value = clause.Expr{SQL: stmt.Quote(v.Field.DBName) + "+1"}
					classUpdated = true
					break
				}
			}
			if !classUpdated {
				assignment := clause.Assignment{
					Column: clause.Column{
						Name: v.Field.DBName,
					},
					Value: clause.Expr{SQL: stmt.Quote(v.Field.DBName) + "+1"},
				}
				newSet := append(set, assignment)
				c.Expression = newSet
				stmt.Clauses["SET"] = c
			}
		}
	}

**Comment by ravirajsdeshmukh** [comment]
Would you be able to make that change?

**Comment by icpd** [comment]
Sorry. I don't plan to change it. 
At the beginning of the plugin development, we already discussed whether this problem should be fixed by GORM or plugin, and finally we chose the former and completed the fix. 
You can fork the plugin repository to make changes to be compatible with older versions of GORM.
