### ISSUE TITLE
Version not being set when primary key is set?

### ISSUE THREAD

**Issue by darewreck54** [go-gorm/optimisticlock#21]
## GORM Playground Link
PR: https://github.com/go-gorm/optimisticlock/pull/22 This reproduces the problem `TestPostgres` passes and `TestPostgres_FailedCase` fails. 

## Description
I took your unit test and just added my own primary key.  When I try to `user.ID = "test1"` add this line to set a primary key, the test values because the version is set to 0.  When i remove that line, the test pass with the version set to 1. 

There is probably something that i'm not understanding with this...
```
type User struct {
	ID      string `gorm:"primarykey"`
	Name    string
	Age     uint
	Version optimisticlock.Version
}

type User struct {
	ID        string `gorm:"primarykey"`
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Age       uint
	Version   optimisticlock.Version
}

func TestPostgres(t *testing.T) {
	DB, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
	require.Nil(t, err)
	_ = DB.Migrator().DropTable(&User{})
	_ = DB.AutoMigrate(&User{})

	user := User{Name: "bob", Age: 20}
	DB.Save(&user)
	require.Equal(t, "bob", user.Name)
	require.Equal(t, uint(20), user.Age)
	require.Equal(t, int64(1), user.Version.Int64)

	rows := DB.Model(&user).Update("age", 18).RowsAffected
	require.Equal(t, int64(1), rows)
	require.Nil(t, DB.First(&user).Error)
	require.Equal(t, int64(2), user.Version.Int64)
	require.Equal(t, uint(18), user.Age)
}

func TestPostgres_FailedCase(t *testing.T) {
	DB, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
	require.Nil(t, err)
	_ = DB.Migrator().DropTable(&User{})
	_ = DB.AutoMigrate(&User{})

	user := User{Name: "bob", Age: 20, ID: "test"}
	DB.Save(&user)
	require.Equal(t, "bob", user.Name)
	require.Equal(t, uint(20), user.Age)
	require.Equal(t, int64(1), user.Version.Int64)

	rows := DB.Model(&user).Update("age", 18).RowsAffected
	require.Equal(t, int64(1), rows)
	require.Nil(t, DB.First(&user).Error)
	require.Equal(t, int64(2), user.Version.Int64)
	require.Equal(t, uint(18), user.Age)
}
```
In the debugger, it looks like the save went through but version is 0.
![image](https://user-images.githubusercontent.com/16171726/215000175-6e8e6889-a585-4df6-a518-8adc5d6eeeaa.png)

When primary key is not set, you can see it set to version 1
![image](https://user-images.githubusercontent.com/16171726/215000306-1aaa7f9a-6a0a-4330-9bed-2c3ccd9df70a.png)

**Comment by darewreck54** [comment]
A workaround is to 
```
	save := DB.Create(&user)
```
instead....not sure why this is the case.

**Comment by icpd** [comment]
Save update value in database, if the value doesn't have primary key, will insert it.
So Create instead of Save will work.

**Comment by darewreck54** [comment]
Yeah, but why does the version not increment when the primary key exist?
________________________________

**Comment by icpd** [comment]
I edited the more detailed reply again. The email content is not the latest. If it is convenient, please check the new content in GitHub. I believe it can help you

**Comment by darewreck54** [comment]
Thanks for the details explanation
