### ISSUE TITLE
什么时候可以搞一个多租户的插件出来呢

### ISSUE THREAD

**Issue by kuangshp** [go-gorm/optimisticlock#32]
期待多租户插件

**Comment by pochapochama** [comment]
不是很懂，请细说

**Comment by kuangshp** [comment]
类似mybatis plus的租户插件，直白点就是在sql语句会自动加一个tenant_id ，在上下文设置值，也可以不加,有点类似deleted_at这个逻辑删除字段一样的

**Comment by pochapochama** [comment]
好像没什么难度啊

**Comment by kuangshp** [comment]
> 看起来参考这个插件就能搞出来

对的，参考这个就可以，只是我比较懒，看看你们官网会出一个吗

**Comment by icpd** [comment]
@jinzhu 是否有必要？
