### ISSUE TITLE
按照示例执行后结果不符合预期

### ISSUE THREAD

**Issue by yxxchange** [go-gorm/optimisticlock#34]
DB.Model(&user).Updates(&User{Age: 18, Version: optimisticlock.Version{Int64: 1}})
// UPDATE `users` SET `age`=18,`version`=`version`+1 WHERE `users`.`version` = 3 AND `id` = 1

上述代码的执行结果是:
UPDATE `users` SET `age`=18,`version`=`version`+1

**Comment by icpd** [comment]
Module传入的user需要有id值哦
