### ISSUE TITLE
更新执行乐观锁报错，converting driver.Value type clause.Expr ("{`app_version`+1 [] false}") to a int64: invalid syntax

### ISSUE THREAD

**Issue by kongyangyang** [go-gorm/optimisticlock#38]
更新数据库记录是，设置的版本号app_version，调用db.Model().Where().Updates().Error出现报错converting driver.Value type clause.Expr ("{`app_version`+1 [] false}") to a int64: invalid syntax

**Comment by icpd** [comment]
能提供一份复现demo吗

**Comment by kongyangyang** [comment]
抱歉 老师，是我的测试问题，老师能请教另外一个问题吗？如果乐观锁冲突这里的错误响应样例是怎样的呀

**Comment by icpd** [comment]
插件内不能获取到SQL执行结果，所以不会有提示。

你可以通过 `RowsAffected` 来判断是否成功修改数据。
